### ISSUE TITLE
RC7 support

### ISSUE THREAD

**Issue by mrkosima** [laco0416/angular2-component-outlet#10]
`@angular.2.0.0-rc.7` contains breaking changes for `angular2-component-outlet`

https://github.com/angular/angular/blob/master/CHANGELOG.md

> core: - all `…Metadata` classes have been removed. Use the corresponding decorator as constructor or for instanceof checks instead.
> Example:
> Before:
> `new ComponentMetadata(…)`
> After:
> `new Component(…)`

**Comment by lacolaco** [comment]
Easy work. I'll tackle it tonight.
