### ISSUE TITLE
(click) is not working: EXCEPTION: Cannot read property 'show' of undefined".

### ISSUE THREAD

**Issue by nkholski** [laco0416/angular2-component-outlet#21]
I scan through texts in my app and use angular2-component-outlet to make links to explain keywords. I alter the texts to call a method in a service and everything worked great until I updated the npm-package from 0.0.4 to 2.0.1.

Template:
`<div *componentOutlet="htmltext; context: self; selector: 'parsed-page-body'"></div>`

htmltext is something like this: 
`Some random text <button (click)="UI.show('difficultword')">difficult word</a> more text.`

It renders OK but when I click the button Chrome console throws: "error_handler.js:45 EXCEPTION: Cannot read property 'show' of undefined".

I've confirmed that "self.UI" exists by adding {{ self.UI | json }} immediatly after closing the div, and by hard-typing a button to the template.

Have I missed something in the update or is it a bug?

**Comment by j-moeller** [comment]
Try `Some random text <button (click)="context.UI.show('difficultword')">difficult word</a> more text.` instead.

See #8 for more information.

Sorry for the inconvenience

**Comment by nkholski** [comment]
Don't know why I didn't think of trying that. Problem solved. Thanks!

**Comment by j-moeller** [comment]
As of #24 "context." is no longer needed.
