### ISSUE TITLE
Components in the html - error

### ISSUE THREAD

**Issue by demiro** [laco0416/angular2-component-outlet#22]
So, what I want to do is to compile the components on the fly... and your solution seems to be perfect for it.... but....

it fails if I have components in the html template

what I was doing was this:

I would get some HTML from the API like this:

```
<page-component-test></page-component-test>
<h2>Some title<h2>
<p>Lorem ipsum text</p>
```

and right now I am using something like:
`this.pageContent = API.response;`

and then in the view:

`<div [innerHTML]="pageContent"></div>`

How would I render the response and create the components that are in there?

if I pass in your directive:
`<div *componentOutlet="pageContent; context: self; selector:'my-component'"></div>`

I am getting this error:

> 'page-component-test' is not a known element:
> 1. If 'page-component-test' is an Angular component, then verify that it is part of this module.
> 2. If 'page-component-test' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("[ERROR ->]<page-component-test></page-component-test>

even if I have PageComponentTest declared in my module (under declarations)...

**Comment by j-moeller** [comment]
For working example see [this](https://github.com/laco0416/angular2-component-outlet/issues/14#issuecomment-246984359).

I think you might be missing

```
    providers: [
        provideComponentOutletModule({
            imports: [DynamicModule]
        })
    ],
```

in your AppModule

**Comment by demiro** [comment]
@j-moeller : sadly changes nothing... still the same problem... :'(

**Comment by j-moeller** [comment]
Could you provide a minimal example?

**Comment by lacolaco** [comment]
I want a repro. You can use a base plunker if you need.
https://plnkr.co/edit/dhRQ3U?p=preview

**Comment by demiro** [comment]
@laco0416 : would love to do it but it's blocked by the corporate here :/
Will try to put the fiels in, since I cannot see the result

**Comment by demiro** [comment]
Here... 
[https://plnkr.co/edit/db7ucK?p=preview](url)

I added page-component-test, I have no idea if it works or not in the plunker since I cannot execute there, please let me know f it works there, so I can 100% assume the problem is on my side here

**Comment by lacolaco** [comment]
I fixed your plunker and then it seems working well.
1. `page-component-test.ts` -> `src/page-component-test.ts` (also .html)
2. `template: require('./page-component-test.html')` -> `templateUrl: 'src/page-component-test.html'`
3. use `provideComponentOutletModule({declarations})`

```
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App, ComponentOutlet ],
  providers: [provideComponentOutletModule({
    declarations:[ PageComponentTest ]
  })],
  bootstrap: [ App ]
})
```

https://plnkr.co/edit/RJbFzg?p=preview

**Comment by demiro** [comment]
Good, thanks... it works as it suppose to... Embarrassed to say the problem was on my side :(
All good now, thanks for your time!

**Comment by demiro** [comment]
well, the problem here (that's why the error) I cannot have it both ways...

In my templates I cannot use PageComponentTest, only via the Outlet component...

it works, if I put it in declarations array in NgModule, but then I get an error, that is decalared 2x!

**Comment by demiro** [comment]
it seems there is an error with assigning properties via host

```
@Component({
                        selector: 'article-item',
        template: require('./article-item.html'),
        host: {
                '[parentList]': 'list'
        }
})
export class ArticleItem implements OnInit {
        @Input() parentList: any;
        constructor(){}
        ngOnInit(){
                console.log("LIST", this.parentList);
        }
}
```

throws this error:

> Can't bind to 'parentList' since it isn't a known property of 'article-item'.
> 1. If 'article-item' is an Angular component and it has 'parentList' input, then verify that it is part of this module.
> 2. If 'article-item' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
