### ISSUE TITLE
[Suggestion] Assign context to component instance

### ISSUE THREAD

**Issue by tolemac** [laco0416/angular2-component-outlet#23]
@laco0416 what do you think about assign context to the component instance instead assign context to `context` property?

Now you create the component this way:

``` typescript
const cmpClass = class _ implements OnDestroy {
      context = ctx;

      ngOnDestroy() {
        ctx = null;
      }
```

I think that is better assign context to component instance when is created, this way:

``` typescript
this.component = this.vcRef.createComponent(cmpFactory, 0, injector);
          this.component.changeDetectorRef.detectChanges();
Object.assign(this.component.instance, context)
```

Then you can access to the context properties directly from template without use `context.` preffix.

For example: 

``` html
<div *componentOutlet="'<div>{{name}}</div>'; context: {name: 'Javier Ros'}; selector:'dym-compo'"></div>
```

Instead: 

``` html
<div *componentOutlet="'<div>{{context.name}}</div>'; context: {name: 'Javier Ros'}; selector:'dym-compo'"></div>
```

What do you think?

**Comment by lacolaco** [comment]
Seems good. Could you make a PR?

**Comment by tolemac** [comment]
Of course.

I have other ideas about to add ngInclude functionality to this repo, I have wrote about that here: https://github.com/angular/angular/issues/7596#issuecomment-252194788

I will tell you whenever I can.
