### ISSUE TITLE
Type _ is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by zkorz** [laco0416/angular2-component-outlet#27]
The plugin is working great for me unless I try to have TWO dynamically created elements on the same page. I am getting the following error:

EXCEPTION: Uncaught (in promise): Error: Type _ is part of the declarations of 2 modules: _ and _! Please consider moving _ to a higher module that imports _ and _. You can also create a new NgModule that exports and includes _ then import that NgModule in _ and _.

I am using Angular 2.0.1

**Comment by lacolaco** [comment]
I want a repro. You can use a base plunker if you need.
https://plnkr.co/edit/dhRQ3U?p=preview

**Comment by zkorz** [comment]
I can reproduced it here:
https://plnkr.co/edit/5WkbWt?p=preview

I figured out how to make my program work. I had set a declarations in the provider to declare components I would need. Instead I put the required components in a module and imported it, but I left the declarations as an empty array. As soon as I removed the declarations the program was able to work with two instances of ng-component.

providers: [provideComponentOutletModule({ declarations: [] })]

Thanks for your help!

**Comment by lacolaco** [comment]
@zkorz Thank you. I confirmed the problem. probably this is a bug of ComponentOutlet.

**Comment by lacolaco** [comment]
Fixed in v3.0.1

**Comment by CorvusCorrax** [comment]
Same problem when using `provideComponentOutletModule({ declarations: [someComponent] })`
Plunker : https://plnkr.co/edit/yOmMi4JqipRT6kzqn5Bp?p=preview

**Comment by atiertant** [comment]
@laco0416 this is working when using a ngmodule importing and exporting components then add in provideComponentOutletModule imports
