### ISSUE TITLE
export ComponentOutlet error

### ISSUE THREAD

**Issue by scottopolis** [laco0416/angular2-component-outlet#29]
Hi, thanks for your work here.

I am using this with Ionic 2, which uses rollup js for compiling.  I have followed the instructions to install component outlet, and I get this error when compiling:

`Module .../node_modules/angular2-component-outlet/index.js does not export ComponentOutlet (imported by .../src/app/app.module.ts)`

My app.module.ts file looks like this:

```
import {ComponentOutlet, provideComponentOutletModule} from 'angular2-component-outlet';

@NgModule({
  declarations: [  ComponentOutlet ],
  providers: [ provideComponentOutletModule({}) ],
  bootstrap: [IonicApp],
  entryComponents: [ ... etc.
})
```

I am not using the root component to render my dynamic template, I am using this in a child component (not sure if that matters). My component is pretty standard:

```
@Component({
  selector: 'custom-page',
  template: `
    <div *componentOutlet="template; context: self; selector:'my-component'"></div>
  `
})
export class CustomPage {

    template = `<h2>Hello {{name}}</h2>`
    context = {
        name: 'Angular 2'
    }

}
```

Any ideas?

**Comment by lacolaco** [comment]
angular2-component-outlet is only publishing a **commonjs** module. AFAIK, Rollup doesn't support commonjs module at default.
