### ISSUE TITLE
RC6: Error of multiple usage component outlet

### ISSUE THREAD

**Issue by mrkosima** [laco0416/angular2-component-outlet#5]
There is error when adding multiple ComponentOutlets:
`core.umd.js:5995 EXCEPTION: Error in ./DynamicComponent class DynamicComponent - inline template:1:10 caused by: Type _ is part of the declarations of 2 modules: _ and _!`

http://embed.plnkr.co/vTTRaWC4oOuU5TSZxLfk/

**Comment by alexwizp** [comment]
I have the same problem

**Comment by j-moeller** [comment]
@dagilleland 's version is still working:

https://github.com/Sandboxed-Forks/angular2-component-outlet/blob/611e02de8ab46f672f4bb154d37bd040efe8a573/src/component-outlet.ts

https://plnkr.co/edit/CI4N18a3Blf6htJffnWa?p=preview

btw:
Don't forget the `self = this;` in DynamicComponent

**Comment by mrkosima** [comment]
@j-moeller thanks for the update!
added `self = this` into my plunker, issue reproduced

Are @dagilleland's changes going to be merged into this repo?

**Comment by j-moeller** [comment]
AFAIK the current version was made by @laco0416 based on the dagilleland version (see also: https://github.com/laco0416/angular2-component-outlet/pull/4)

**Comment by mrkosima** [comment]
ok, let's wait some inputs from @laco0416

**Comment by j-moeller** [comment]
The moduleMeta is the same for every Outlet, thus we're pushing the same component multiple times to the declarations array (see my code-comment above). Copying the moduleMeta in the constructor quick-fixes this.

https://plnkr.co/edit/QtvYyn2Clhbi8vNdE2Pv?p=preview

**Comment by mrkosima** [comment]
Thanks for quick fix, it looks good for me
Hope this will be included in new version soon

**Comment by lacolaco** [comment]
Thank you very much. I'll tackle to this tonight.

2016/09/06 21:16 "Kanstantsin Klimashevich" notifications@github.com:

**Comment by lacolaco** [comment]
Fixed in v0.1.2.
