### ISSUE TITLE
Angular Pipes RC6?

### ISSUE THREAD

**Issue by RobArbor** [laco0416/angular2-component-outlet#7]
Before RC 6 i was able to use pipes in my dynamic templates.
Any idea if this is still possible? 
Normal curly based variables still work. 

I think it fails because the dynamic component is loaded in a separate module.
instead of the same like in the RC5 version.

Tried passing them in the declarations property of the `provideComponentOutletModule`.

**Comment by j-moeller** [comment]
Have you tried wrapping your pipes in a separate module and passing it as an import-module?

btw: If you pass the pipes via declarations, you may get an error, when you're using the same component twice. see: #6

**Comment by RobArbor** [comment]
Tanks for pointing me in the right direction!

Created a pipe:

```
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({ name: 'dummy' })

export class DummyPipe implements PipeTransform {
    transform(value: string): string {
        return "hello world";
    }
}
```

A module for it:

```
import { NgModule } from '@angular/core';
import { DummyPipe } from './dummy.pipe' 

@NgModule({ declarations: [DummyPipe], exports: [DummyPipe] })
export class PipeModule { }`
```

And i could import the module in both my main module and the `provideComponentOutletModule`!
